spring.application.name=spotifytracker

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/spotifytracker
spring.datasource.username=postgres

# Hibernate auto-creates tables from your entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Spotify OAuth credentials (get these from developer.spotify.com)
#spring.security.oauth2.client.registration.spotify.scope=user-read-recently-played,user-top-read
#spring.security.oauth2.client.registration.spotify.authorization-grant-type=authorization_code
#spring.security.oauth2.client.provider.spotify.authorization-uri=https://accounts.spotify.com/authorize
#spring.security.oauth2.client.provider.spotify.token-uri=https://accounts.spotify.com/api/token
#spring.security.oauth2.client.provider.spotify.user-info-uri=https://api.spotify.com/v1/me
#spring.security.oauth2.client.provider.spotify.user-name-attribute=id
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration,org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration

# Spring Boot to run with self-signed SSL certifacte 
#server.ssl.enabled=true
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=changeit

# Adds local application properties file on top
spring.profiles.active=local
